### ISSUE TITLE
MMS download fails with: Invalid URL: ''

### ISSUE THREAD

**Issue by jackmcdougal** [ubports/nuntium#14]
On unrelated note, I came here trying to debug push parsing issue with Tele2 SE: https://paste.ubuntu.com/p/QhCd57JGsB/. It seems to fail with Download issues: org.freedesktop.DBus.Error.InvalidArgs: Invalid URL: '' on both original and your rewrite, so not directly related, but maybe you have an idea what could be wrong given the scope of changes.

_Originally posted by @NotKit in https://github.com/ubports/nuntium/issues/8#issuecomment-856001018_

@Notkit, did you ever resolve this issue?  I am having it as well ... on most recent Dev channel.   Thanks!

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/nuntium/-/issues/14

Sorry for your inconvenience.
