### ISSUE TITLE
Launchpad references in debian packaging

### ISSUE THREAD

**Issue by jezek** [ubports/nuntium#16]
Hello, I see some launchpad references in debian.

```
$ grep -r launchpad debian
debian/copyright:Source: https://launchpad.net/nuntium
debian/control:Homepage: https://launchpad.net/nuntium
debian/control:Vcs-Browser: http://bazaar.launchpad.net/~phablet-team/packaging/trunk/files
debian/rules:#https://bugs.launchpad.net/ubuntu/+source/dh-golang/+bug/1911911
```

Are they actual? Should it not point to ubports github?

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/nuntium/-/issues/16

Sorry for your inconvenience.
