### ISSUE TITLE
can't fetch MMS sometimes

### ISSUE THREAD

**Issue by lduboeuf** [ubports/nuntium#18]
Just had an issue today.
Received a normal notification, activate the data, press on the Download button, then  i had infinite loading. 
Deleted the message and received the more verbose error with download button, but no way to retrieve the MMS.

Here is the log for nuntium:
![screenshot20220212_124236351](https://user-images.githubusercontent.com/11663835/153710077-fa6effdf-f7d0-4900-ba6c-fe7acd39ed09.png)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/nuntium/-/issues/18

Sorry for your inconvenience.
